version: '3.9'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: apps/space-token-hunt/Dockerfile.dev
    ports:
      - "3002:3002"
    env_file:
      - .env.dev
    depends_on:
      - postgres
      - redis
    restart: always

  redis:
    container_name: space-token-hunt-redis
    image: redis:6.2-rc-alpine
    env_file:
      - .env.dev
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass zy2DHP4VC6NgjXAv

  postgres:
    container_name: space-token-hunt-pg
    image: postgres:14
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    restart: always

  nginx_dev:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx_dev
    restart: on-failure
    env_file:
      - .env
    ports:
      - "443:443"