FROM nginx:1.21-alpine

COPY nginx.conf /etc/nginx/templates/nginx.conf.template
RUN mkdir -p /etc/letsencrypt/live/space-token-hunt-be.sky-tehnol.uk
COPY fullchain.pem /etc/letsencrypt/live/space-token-hunt-be.sky-tehnol.uk/fullchain.pem
COPY privkey.pem /etc/letsencrypt/live/space-token-hunt-be.sky-tehnol.uk/privkey.pem
