export const config = {
  THIRD_WEB_API: process.env.NEXT_PUBLIC_THIRD_WEB_API,
  INFURA_API_KEY: process.env.NEXT_PUBLIC_INFURA_API_KEY,
  WC_PROJECT_ID: process.env.NEXT_PUBLIC_WC_PROJECT_ID,
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
};
